---
title: "Codice"
author: "Massimiliano Baldo"
date: "19/8/2020"
output: ioslides_presentation

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(modelr)

## Set completo dei dati sui Pokemon
set <- read.csv("./sets/Pokedex_Ver3.csv")

## Set con le debolezze dei pokemon
aux_set <- read.csv("./sets/dataset_pokemon.csv")
```


```{r}
## Prima Domanda 
## Which type is the strongest overall? Which is the weakest? 

### Creazione della Weak Table
weak_table <- aux_set %>%
  select(type1, type2, contains("against")) %>%
  filter(type2 == "") %>%
  distinct() %>% ## make only one type for row because are identicaly
  select(-type2) %>%
  rename(type = type1)
```

```{r}
### Somma dei Punti
sum <- weak_table %>%
  select(-type) %>%
  rowSums()

weak_table %>%
  select(-contains("against")) %>%
  mutate(sum = sum) %>%
  arrange(sum)
```


```{r}
## Seconda Domanda
## Which double-type exisitng is the strongest overall? Which is the weakest? 

#### Creazione della Double Weak Table
double_weak_table <- aux_set %>%
  select(type1, type2, contains("against")) %>%
  filter(type2 != "") %>%
  distinct()
```

```{r}
### Somma dei Punti
sum <- double_weak_table %>%
  select(-contains("type")) %>%
  rowSums()

double_weak_table %>%
  select(-contains("against")) %>%
  mutate(sum = sum) %>%
  arrange(sum)
```


```{r}
## Terza Domanda 
## Which type is the most likely to be a legendary Pokemon? 

## Ricerca dei pokemon leggendari
legendary <- set %>%
  select(NAME, TYPE1, TYPE2, LEGENDARY) %>%
  filter(LEGENDARY == TRUE) %>%
  distinct() ## necessario poichè alucni pokemon come Deoxsy cambiano forma ma non tipo
```


```{r}
### Trovare il Tipo che risulta più frequente
t1 <- as.data.frame(table(legendary$TYPE1)) 
t2 <- as.data.frame(table(legendary$TYPE2, exclude = "")) 

legendary_type_sum <- full_join(t1, t2, by = "Var1") %>%
  select(-Var1) %>%
  rowSums()

t1 %>%
  rename(TYPE = Var1) %>%
  select(-Freq) %>%
  mutate(SUM = legendary_type_sum) %>%
  arrange(SUM)
```

```{r}
### Verifica
legendary %>%
  filter(TYPE1 == "Psychic" | TYPE2 == "Psychic")
```


```{r}
## Quarta Domanda 
## How does height and weight of a Pokemon correlate with its various base stats? 
ggplot(data = set, mapping = aes(x = HEIGHT, y = HP)) +
  geom_point() +
  geom_smooth()

height_cor <- as.data.frame(c(cor(set$HEIGHT, set$HP), 
                              cor(set$HEIGHT, set$ATK),
                              cor(set$HEIGHT, set$DEF),
                              cor(set$HEIGHT, set$SP_ATK),
                              cor(set$HEIGHT, set$SP_DEF),
                              cor(set$HEIGHT, set$SPD)))

weigth_cor <- as.data.frame(c(cor(set$WEIGHT, set$HP), 
                              cor(set$WEIGHT, set$ATK),
                              cor(set$WEIGHT, set$DEF),
                              cor(set$WEIGHT, set$SP_ATK),
                              cor(set$WEIGHT, set$SP_DEF),
                              cor(set$WEIGHT, set$SPD)))

pairs(set[, c(15, 16, 17, 18, 19, 20, 21)])
```

```{r}
library(corrplot)

# Correlazione tra peso e gli stati
corrplot(cor(set[, c(15, 16, 17, 18, 19, 20, 21)]),
  method = "number",
  type = "upper" # show only upper side
)

```

```{r}
# Correlazione tra altezza e gli stati
corrplot(cor(set[, c(14, 16, 17, 18, 19, 20, 21)]),
  method = "number",
  type = "upper" 
)

```

```{r}
# Proviam Quadrata
quad_height <- set[, c(14)] ^ 2
quad_weight <- set[, c(15)] ^ 2

corrplot(cor(quad_height, set[, c(16, 17, 18, 19, 20, 21)]),
  method = "number",
  type = "upper" # show only upper side
)

corrplot(cor(quad_weight, set[, c(16, 17, 18, 19, 20, 21)]),
  method = "number",
  type = "upper" # show only upper side
)

```

```{r}
# Proviam Log
log_height <- set[, c(14)] %>% log()
log_weight <- set[, c(15)] %>% log()

corrplot(cor(log_height, set[, c(16, 17, 18, 19, 20, 21)]),
  method = "number",
  type = "upper" # show only upper side
)

corrplot(cor(log_weight, set[, c(16, 17, 18, 19, 20, 21)]),
  method = "number",
  type = "upper" # show only upper side
)
```

```{r}
# Mostriamo Log
ggplot(data = set, mapping = aes(log_height, ATK)) +
  geom_point() +
  geom_smooth()
```


```{r}
# Ultima Domanda 
# Can you build a Pokemon dream team? A team of 6 Pokemon that inflicts the most damage while remaining relatively impervious to any other team of 6 Pokemon.
# Cerchiamo una combinazione di pokemon la quale abbia una ampia "copertura" dai vari attacchi
# Dobbiamo considerare le debolezze e moltiplicarle tra loro

#dream_team <- aux_set[, 2:19] %>%
  #rowwise() %>%
  #mutate(Product = prod(c_across("against_bug":"against_water"))) %>%
  #filter(Product == 0) 
  

cond <- aux_set$against_bug == 0 |
  aux_set$against_dragon == 0 |
  aux_set$against_dark == 0 |
  aux_set$against_electric == 0 |
  aux_set$against_fairy == 0 |
  aux_set$against_fight == 0 |
  aux_set$against_fire == 0 |
  aux_set$against_flying == 0 |
  aux_set$against_ghost == 0 |
  aux_set$against_grass == 0 |
  aux_set$against_ground == 0 |
  aux_set$against_ice == 0 |
  aux_set$against_normal == 0 |
  aux_set$against_poison == 0 |
  aux_set$against_psychic == 0 |
  aux_set$against_rock == 0 |
  aux_set$against_steel == 0 |
  aux_set$against_water == 0 
  
  
best_candidates <- aux_set %>%
  select(name, contains("against"))


## Selezionare quelli che hanno presente almeno un zero nelle colonne delle debolezze
#y <- aux_set[ which(cond), ] #[, 2:19]

x <- best_candidates %>%
  filter(rowSums(best_candidates == 0) > 0)
  

## Scegliere quello che ha la somma più bassa
x <- x %>%
  rowwise() %>%
  mutate(Sum = sum(c_across("against_bug":"against_water"))) %>%
  arrange(Sum)

dream_team <- head(x, 1)
  
## Da lui, cercare un altro pokemon che compensi le debolezze del primo
any(x$against_ground %in% 0)

# Skarmory
new_member <- x %>%
  filter(against_ground == 0) %>%
  arrange(Sum) %>%
  head(1)

dream_team <- rbind(dream_team, new_member)

# --- #

any(x$against_fire %in% 0)
any(x$against_fire %in% 0.5)

# Marill -> Azumarill
new_member <- x %>%
  filter(against_fire == 0.5) %>%
  arrange(Sum) %>%
  head(1)


dream_team <- rbind(dream_team, new_member)

# ---#

any(x$against_electric %in% 0)

# Steelix
new_member <- x %>%
  filter(against_electric == 0) %>%
  arrange(Sum) %>%
  head(1)

dream_team <- rbind(dream_team, new_member)

# ---#
any(x$against_fight %in% 0)

new_member <- x %>%
  filter(against_fight == 0) %>%
  arrange(Sum) %>%
  head(1)

# Honedge --> Aegislash
dream_team <- rbind(dream_team, new_member)


# --- #
any(x$against_dark %in% 0.5)
# ritorna <maehile, che abbiam già in squadra

new_member <- x %>%
  filter(against_water == 0.5) %>%
  arrange(Sum) %>%
  head(2)  ## Sarebbe Dialga, però considerare pokemon leggendari nella ricerca non è funzionale al fine di tale, pertanto usaim il secondo che è anche uno starter

dream_team <- rbind(dream_team, new_member[2, ])

final_team <- aux_set %>%
  filter(name %in% dream_team$name)  %>%
  select(name, type1, type2, hp, attack, defense, speed, sp_attack, sp_defense)

head(final_team)

```


```{r}
# Usiam le evoluzioni finali

final_team[1,] <-aux_set %>%
  select(name, type1, type2, hp, attack, defense, speed, sp_attack, sp_defense) %>%
  filter(name == "Azumarill")

final_team[6,] <-aux_set %>%
  select(name, type1, type2, hp, attack, defense, speed, sp_attack, sp_defense) %>%
  filter(name == "Aegislash")

final_team
```

















